config/routes.rb
Locksmith::Engine.routes.draw do
  root 'applications#index'

  resources :applications, only: [:new, :create, :show, :destroy]
  post 'applications/:id'        => 'applications#regenerate',  as: :regenerate
  get 'applications/:id/delete'  => 'applications#delete',      as: :delete_application

  get    'signin'   => 'session#new'
  post   'signin'   => 'session#create'
  delete 'signout'  => 'session#destroy'

  get 'signup'   => 'users#new'
  post 'signup'  => 'users#create', as: :users

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :applications, only: [:show, :destroy]
    post 'applications/:id'        => 'applications#regenerate',  as: :regenerate
    get 'applications/:id/delete'  => 'applications#delete',      as: :delete_application
  end
end

app/models/locksmith/application.rb
module Locksmith
  class Application < ActiveRecord::Base
    belongs_to :user

    validates_presence_of :user
    validates_presence_of :name
    validates :key, presence: true, uniqueness: true

    after_initialize do
      regenerate_key if self.key.nil?
    end

    def regenerate_key
      self.key = SecureRandom.hex
    end
  end
end

app/models/locksmith/user.rb
module Locksmith
  require 'email_validator/strict'

  class User < ActiveRecord::Base
    has_secure_password
    has_many :applications

    validates_presence_of :name

    validates :email,
              presence: true,
              email: { message: 'must be valid' },
              uniqueness: { case_sensitive: false }

    before_save { self.email.downcase! }
  end
end

app/controllers/locksmith/admin/admin_controller.rb
require_dependency 'locksmith/application_controller'

module Locksmith
  module Admin
    class AdminController < ApplicationController
      before_action :validate_admin

      private

      def validate_admin
        unless admin?
          flash[:error] = 'You don\'t have access to that page'
          redirect_to root_path
        end
      end
    end
  end
end

app/controllers/locksmith/admin/applications_controller.rb
require_dependency 'locksmith/application_controller'

module Locksmith
  module Admin
    class ApplicationsController < AdminController
      def delete
        @application = Application.find(params[:id])
      end

      def destroy
        application = Application.find(params[:id])
        application.destroy
        flash[:success] = 'The application have been deleted'
        redirect_to admin_user_path(application.user_id)
      end

      def show
        @application = Application.find(params[:id])
      end

      def regenerate
        application = Application.find(params[:id])
        application.regenerate_key
        application.save
        redirect_to show
      end
    end
  end
end

app/controllers/locksmith/admin/users_controller.rb
require_dependency 'locksmith/application_controller'

module Locksmith
  module Admin
    class UsersController < AdminController
      def destroy
        @user = User.find params[:id]
        @user.destroy
        redirect_to admin_users_path
      end

      def index
        @users = User.all
      end

      def show
        @user = User.find params[:id]
      end
    end
  end
end

app/controllers/locksmith/application_controller.rb
module Locksmith
  class ApplicationController < ActionController::Base
    before_action :validate_logged_in
    protect_from_forgery with: :exception

    include SessionHelper

    private

    # Validates that the user is signed in and redirects to signin form if needed
    def validate_logged_in
      unless signed_in?
        flash[:error] = 'You need to sign in' unless request.path == root_path
        redirect_to signin_path
      end
    end
  end
end

app/controllers/locksmith/applications_controller.rb
require_dependency 'locksmith/application_controller'

module Locksmith
  class ApplicationsController < ApplicationController
    def create
      @application = Application.new(name: params[:application][:name], user: current_user)
      if @application.save
        flash[:success] = 'Your application have been created'
        redirect_to application_path(@application)
      else
        render 'new'
      end
    end

    def delete
      @application = Application.find(params[:id])
    end

    def destroy
      Application.destroy(params[:id])
      flash[:success] = 'Your application have been deleted'
      redirect_to root_path
    end

    def index
      @applications = Application.where(user: current_user)
    end

    def new
      @application = Application.new
    end

    def show
      @application = Application.find(params[:id])
    end

    def regenerate
      application = Application.find(params[:id])
      application.regenerate_key
      application.save
      redirect_to show
    end

    private

    def application_params
      params.require(:application).permit(:name)
    end
  end
end

app/controllers/locksmith/session_controller.rb
require_dependency 'locksmith/application_controller'

module Locksmith
  class SessionController < ApplicationController
    skip_before_action :validate_logged_in, only: [:create, :new]
    before_action :validate_guest, only: [:create, :new]

    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        sign_in user
        flash[:success] = 'You have successfully signed in'
        redirect_to root_path
      else
        flash.now[:error] = 'Invalid email and password combination'
        render 'new'
      end
    end

    def destroy
      reset_session
      sign_out
      flash[:success] = 'You have successfully signed out'
      redirect_to signin_path
    end

    def new
      # Just show view
    end

    private

    def validate_guest
      redirect_to root_path if signed_in?
    end
  end
end

app/controllers/locksmith/users_controller.rb
require_dependency 'locksmith/application_controller'

module Locksmith
  class UsersController < ApplicationController
    skip_before_action :validate_logged_in, only: [:create, :new]
    before_action :validate_guest

    def create
      @user = User.new(user_params)
      if @user.save
        sign_in @user
        flash[:success] = 'Your account have been created'
        redirect_to root_path
      else
        render 'new'
      end
    end

    def new
      @user = User.new
    end

    private

    def validate_guest
      redirect_to root_path if signed_in?
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/helpers/locksmith/api_helper.rb
module Locksmith
  module ApiHelper
    class InvalidKey < StandardError
    end

    def self.validate_key(key)
      application = Application.where(key: key).first

      raise InvalidKey if application.nil?
    end
  end
end

app/helpers/locksmith/application_helper.rb
module Locksmith
  module ApplicationHelper
    # Displays the validation errors for the specified model and attribute if there are any
    def errors_for(model, attribute, name = nil)
      name = attribute.capitalize if name.nil?

      if model.errors[attribute].present?
        content_tag(:ul, class: 'errors') do
          # Loop over every error
          model.errors.messages[attribute].map do |error|
            # Display the error and the field name
            content_tag(:li, "#{name} #{error}")
          # Concatenate the li tags using reduce to not make outer content_tag escape the inner
          end.reduce(:<<)
        end
      end
    end
  end
end

app/helpers/locksmith/session_helper.rb
module Locksmith
  module SessionHelper
    # Returns the current signed-in user, nil if no user is signed in
    def current_user
      @current_user ||= User.find_by id: session[:user_id]
    end

    # Returns true if a user is signed in, false otherwise.
    def signed_in?
      current_user.present?
    end

    def admin?
      return false unless signed_in?
      current_user.admin
    end

    # Signs in the given user.
    def sign_in(user)
      session[:user_id] = user.id
    end

    # Signs out the current user.
    def sign_out
      session.delete :user_id
      @current_user = nil
    end
  end
end

app/views/layouts/locksmith/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locksmith</title>
  <%= stylesheet_link_tag    'locksmith/application', media: 'all' %>
  <%= javascript_include_tag 'locksmith/application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
      <p class="flash <%= type %>"><%= message %></p>
  <% end %>
  <nav>
    <% if admin? %>
        <%= link_to 'Users', admin_users_path %>
    <% end %>
    <% if signed_in? %>
        <%= link_to 'My applications', root_path %>
        <%= form_tag signout_path, method: :delete do %>
            <%= submit_tag 'Sign out' %>
        <% end %>
    <% end %>
  </nav>

  <main>
    <%= yield %>
  </main>
  <div class="auth-box">
    <%= yield 'auth' %>
  </div>
  <!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>

app/views/locksmith/admin/applications/delete.html.erb
<h2>Are you sure that you want to delete <%= @application.name %>?</h2>

<%= form_tag admin_application_path(@application), method: :delete do %>
    <%= submit_tag 'Yes, I\'m sure', class: 'danger' %>
    <%= link_to 'No, go back', admin_application_path(@application), class: 'button' %>
<% end %>

app/views/locksmith/admin/applications/show.html.erb
<h1><%= @application.name %></h1>

Key: <pre><%= @application.key %></pre>
<%= form_tag admin_regenerate_path, method: :post do %>
    <%= submit_tag 'Regenerate' %>
    <%= link_to 'Delete application', admin_delete_application_path(@application), class: 'button danger' %>
<% end %>

app/views/locksmith/admin/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
      <li><%= link_to user.name, admin_user_path(user) %></li>
  <% end %>
</ul>

app/views/locksmith/admin/users/show.html.erb
<h1><%= @user.name %></h1>

<ul>
  <% @user.applications.each do |application| %>
      <li><%= link_to application.name, admin_application_path(application) %></li>
  <% end %>
</ul>

<%= form_tag admin_user_path(@user), method: :delete do %>
    <%= submit_tag 'Delete user', class: 'danger' %>
<% end %>

app/views/locksmith/applications/delete.html.erb
<h2>Are you sure that you want to delete <%= @application.name %>?</h2>

<%= form_tag application_path(@application), method: :delete do %>
    <%= submit_tag 'Yes, I\'m sure', class: 'danger' %>
    <%= link_to 'No, go back', application_path(@application), class: 'button' %>
<% end %>

app/views/locksmith/applications/index.html.erb
<h1>Applications</h1>

<ul>
  <% @applications.each do |application| %>
      <li><%= link_to application.name, application_path(application) %></li>
  <% end %>
  <li><%= link_to 'New application', new_application_path %></li>
</ul>

app/views/locksmith/applications/new.html.erb
<h1>New application</h1>

<%= form_for(:application, url: applications_path) do |f| %>
    <%= errors_for @application, :name %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit 'Create application' %>
<% end %>

app/views/locksmith/applications/show.html.erb
<h1><%= @application.name %></h1>

Key: <pre><%= @application.key %></pre>
<%= form_tag regenerate_path, method: :post do %>
    <%= submit_tag 'Regenerate' %>
    <%= link_to 'Delete application', delete_application_path(@application), class: 'button danger' %>
<% end %>

app/views/locksmith/session/new.html.erb
<% provide 'auth' do %>
  <h1>Sign in</h1>

  <%= form_for(:session, url: signin_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit 'Sign in' %>
  <% end %>

  <p>New user? <%= link_to 'Sign up now!', signup_path %></p>
<% end %>

app/views/locksmith/users/new.html.erb
<% provide 'auth' do %>
  <h1>Create account</h1>

  <%= form_for @user do |f| %>
      <%= errors_for @user, :name %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= errors_for @user, :email %>
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= errors_for @user, :password %>
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= errors_for @user, :password_confirmation, 'Confirmation' %>
      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit 'Create account' %>
  <% end %>

  <p>Already have an account? <%= link_to 'Sign in instead', signin_path %>.</p>
<% end %>